### ISSUE TITLE
Delete file doesn't work

### ISSUE THREAD

**Issue by alex285** [snapcrafters/atom#12]
Reproduce

1. Open a project
2. Try to remove a file, either with "delete" key or from Atom's right click menu

Outcome: 
the file isn't deleted

**Snap**
snap    2.27.6+17.10
snapd   2.27.6+17.10
series  16
ubuntu  17.10
kernel  4.13.0-12-generic

***Atom***
1.20.0

**Comment by flexiondotorg** [comment]
The route cause of this issue is that the gvfs binaries have changed recently. `gvfs-trash` is being called by Atom but in recent Linux distributions, such as Ubuntu 17.10, that executable is deprecated and instead of moving files to the trash it now displays at notice and does nothing. The equivalent of `gvfs-trash` is now `gio trash`.

I'll research what the best way to proceed is.

**Comment by guilhem** [comment]
Since https://github.com/electron/electron/pull/9518 we can set variable `ELECTRON_TRASH` to `gio` but atom' electron version is too old.

I opened an issue https://github.com/atom/atom/issues/15949

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/flexiondotorg/atom-1/commit/455850dfac02f611da5714e6240b6dca7f67d2af

**Comment by erayerdin** [comment]
Not fixed. Still having the issue.

***
# Environment

```
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        18.0.4
Codename:       Illyria
```

**Comment by smiddy** [comment]
I have the same problem in

Ubuntu 18.04 64 bit
Atom 1.38.2
